#!/usr/bin/env bash
#displays the content of the file /etc/passwd

File="/etc/passwd"
while IFS=":" read -r usr pass uid gid uinfo homedir shell
do
	echo "The user $usr is part of the $gid gang, lives in $homedir and \
		rides $shell. $uid's place is protected by the passcode $pass, \
		more info about the user here: $uinfo"
done < "$File"
